# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# Mod properties
mod_version = 1.1.1-26.1.2-alpha
maven_group = com.shotadft.more_fixes
archives_name = more_fixes
enabled_platforms = fabric,neoforge

# Minecraft properties
minecraft_version = 26.1.2

# Dependencies
architectury_api_version = 20.0.8
fabric_loader_version = 0.19.3
fabric_api_version = 0.154.2+26.1.2
neoforge_version = 26.1.2.78
