modLoader = "javafml"
loaderVersion = "[2,)"
#issueTrackerURL = ""
license = "MIT"

[[mods]]
modId = "more_fixes"
version = "${version}"
displayName = "More Fixes"
authors = "Shotadft"
description = '''
I'll fix bugs that don't bother me but still bother me.
'''
logoFile = "icon.png"

[[dependencies.more_fixes]]
modId = "neoforge"
type = "required"
versionRange = "[21,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.more_fixes]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.more_fixes]]
modId = "architectury"
type = "required"
versionRange = "[13.0.8,)"
ordering = "AFTER"
side = "BOTH"

[[mixins]]
config = "more_fixes.mixins.json"
